# ===================================================================
# COMMON SPRING BOOT PROPERTIES
#
# This section provides a list common Spring Boot properties and references
# to the underlying classes that consume them
#
# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

# LOGGING
#
# Using log4j2 : https://springframework.guru/using-log4j-2-spring-boot/
#

#
# Docker - Production configuration
#
spring:
    application:
        name: vws-backend
    profiles: container
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: auto
    # MySQL Support: https://spring.io/guides/gs/accessing-data-mysql/
    datasource:        
        url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
        driver-class-name: com.mysql.jdbc.Driver
        
#      
# Actuator: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready   
#
# Estas URL tienen que estar mapeadas en el WebSecurity.java
#
endpoints:
  beans:
    id: springbeans # Renombramos el path /beans a /springbeans
    sensitive: false
  loggers:
    sensitive: false
  metrics:
    sensitive: false
  mappings:
    sensitive: false
  docs:
    sensitive: false
    
# VWS Configuration
general:
  scraping:
    parse:
      maxbillboardfilms: 20
      maxvideopremieres: 20
      maxtvshows: 7
    parsertumejortorrent:
      requestdelay: 303

