# This is a sample build configuration for Java – Maven.
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.3.9

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - mvn -P integration -Dmaven.test.failure.ignore=true install # -B batch mode makes Maven less verbose
    - step:
       script: # Modify the commands below to build your repository.
          - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar  -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=rvillamil-bitbucket  -Dsonar.login=7750fc9fb8a33d688729a9f94d1943393829294f