version: '2.0'
     
services:
   
  service-bbdd:
    image: img-vws-mysql:1.0-SNAPSHOT
    container_name: cnt-vws-mysql    
    environment:
      - MYSQL_ROOT_PASSWORD=root      
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss
    ports:
      - 5306:3306
  
  service-vws-frontend:
    image: img-vws-apache:1.0-SNAPSHOT
    container_name: cnt-vws-apache
    ports:
      - 9090:80
      
  service-vws-backend:
    image: img-vws-resources:1.0-SNAPSHOT      
    container_name: cnt-vws-resources
    depends_on:
      - service-bbdd
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=service-bbdd
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=vws
      - DATABASE_PORT=3306

